name: 'FlagGuard'
description: 'Analyze feature flags for conflicts and dead code'
author: 'FlagGuard Team'
branding:
  icon: 'flag'
  color: 'blue'

inputs:
  config-path:
    description: 'Path to feature flag configuration file'
    required: true
  source-path:
    description: 'Path to source code directory'
    required: true
    default: '.'
  fail-on-critical:
    description: 'Fail the check if critical conflicts are found'
    required: false
    default: 'true'
  output-format:
    description: 'Report format (markdown, json)'
    required: false
    default: 'markdown'
  max-conflicts:
    description: 'Maximum conflicts to report'
    required: false
    default: '50'

outputs:
  conflicts-found:
    description: 'Number of conflicts found'
    value: ${{ steps.analyze.outputs.conflicts-found }}
  critical-count:
    description: 'Number of critical conflicts'
    value: ${{ steps.analyze.outputs.critical-count }}
  report-path:
    description: 'Path to generated report'
    value: ${{ steps.analyze.outputs.report-path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install FlagGuard
      shell: bash
      run: pip install flagguard
    
    - name: Run Analysis
      id: analyze
      shell: bash
      run: |
        REPORT_EXT="${{ inputs.output-format == 'json' && 'json' || 'md' }}"
        
        flagguard analyze \
          --config "${{ inputs.config-path }}" \
          --source "${{ inputs.source-path }}" \
          --output "flagguard-report.${REPORT_EXT}" \
          --format ${{ inputs.output-format }} \
          --no-llm \
          2>&1 | tee flagguard-output.txt || true
        
        # Parse results
        CONFLICTS=$(grep -oP 'Conflicts found: \K\d+' flagguard-output.txt || echo "0")
        CRITICAL=$(grep -c 'CRITICAL' flagguard-output.txt || echo "0")
        
        echo "conflicts-found=$CONFLICTS" >> $GITHUB_OUTPUT
        echo "critical-count=$CRITICAL" >> $GITHUB_OUTPUT
        echo "report-path=flagguard-report.${REPORT_EXT}" >> $GITHUB_OUTPUT
    
    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: flagguard-report
        path: flagguard-report.*
    
    - name: Comment on PR
      if: github.event_name == 'pull_request' && inputs.output-format == 'markdown'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('flagguard-report.md', 'utf8');
          const truncated = report.substring(0, 60000);
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '## 🚩 FlagGuard Analysis\n\n' + truncated
          });
    
    - name: Fail on Critical
      if: inputs.fail-on-critical == 'true'
      shell: bash
      run: |
        if [ "${{ steps.analyze.outputs.critical-count }}" != "0" ]; then
          echo "::error::Critical flag conflicts detected!"
          exit 1
        fi
