name: Bug Report
description: Report a bug in FlagGuard
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Describe the bug...
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `flagguard analyze ...`
        2. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: FlagGuard Version
      placeholder: "0.1.0"
    validations:
      required: true
  
  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "3.11"
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  
  - type: textarea
    id: config
    attributes:
      label: Configuration File (if relevant)
      description: Share your flag config (anonymized if needed)
      render: json
