name: Feature Request
description: Suggest a new feature for FlagGuard
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature request! Please fill out the form below.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see?
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?
  
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Parser (new format support)
        - Analysis (new detection type)
        - CLI (new command/option)
        - Web UI
        - Documentation
        - CI/CD Integration
        - Other
    validations:
      required: true
