"""Ollama Modelfile Generator & Deployment Guide (Phase 3 — Step 3.5).

Generates an Ollama Modelfile for serving the fine-tuned FlagGuard-Coder model
locally, and provides a structured guide for merging LoRA adapters to GGUF format.

Deployment Pipeline:
    1. [Colab/GPU] Merge LoRA adapters into the base model and export as GGUF:
           model.save_pretrained_gguf("models/", tokenizer, quantization_method="q4_k_m")

    2. [Local] Generate the Ollama Modelfile:
           python scripts/export_gguf.py --lora-dir models/flagguard-dpo-lora

    3. [Local] Register the model with Ollama:
           ollama create flagguard-coder -f models/Modelfile

    4. [Automatic] FlagGuard's OllamaClient will detect flagguard-coder:latest
       on startup and automatically use it instead of the default model.

    5. [Verification] Test the deployed model:
           ollama run flagguard-coder "Explain a mutual exclusion conflict between dark_mode and premium_tier"

Usage:
    python scripts/export_gguf.py --lora-dir models/flagguard-dpo-lora
    python scripts/export_gguf.py --lora-dir models/flagguard-dpo-lora --quant q8_0
    python scripts/export_gguf.py --dry-run  # print Modelfile without writing
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import textwrap
import time
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger("flagguard.export")

# Supported quantization levels and their VRAM requirements
QUANT_OPTIONS: dict[str, dict] = {
    "q4_k_m":  {"desc": "4-bit (recommended)",  "vram_gb": 5.5,  "quality": "high"},
    "q5_k_m":  {"desc": "5-bit (quality+)",     "vram_gb": 6.5,  "quality": "very high"},
    "q8_0":    {"desc": "8-bit (near lossless)", "vram_gb": 9.5,  "quality": "near-lossless"},
    "f16":     {"desc": "16-bit (full quality)", "vram_gb": 16.0, "quality": "lossless"},
    "q2_k":    {"desc": "2-bit (low VRAM)",      "vram_gb": 3.0,  "quality": "low"},
}

MODELFILE_TEMPLATE = textwrap.dedent("""\
    # FlagGuard-Coder Ollama Modelfile
    # Generated by: scripts/export_gguf.py
    # Timestamp: {timestamp}
    # Base model: {base_model}
    # Quantization: {quant}
    # Training: SFT (QLoRA r=16) + DPO (beta=0.1)

    FROM ./{gguf_filename}

    # ── Context & Sampling ──────────────────────────────────────────────────
    PARAMETER num_ctx 4096
    PARAMETER temperature 0.3
    PARAMETER top_p 0.9
    PARAMETER top_k 40
    PARAMETER repeat_penalty 1.1
    PARAMETER stop "<|eot_id|>"
    PARAMETER stop "<|end_of_text|>"

    # ── Llama-3 ChatML Template ─────────────────────────────────────────────
    TEMPLATE \"\"\"
    {{{{ if .System }}}}<|begin_of_text|><|start_header_id|>system<|end_header_id|>

    {{{{ .System }}}}<|eot_id|>{{{{ end }}}}<|start_header_id|>user<|end_header_id|>

    {{{{ .Prompt }}}}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

    \"\"\"

    # ── Domain System Prompt ────────────────────────────────────────────────
    SYSTEM \"\"\"You are FlagGuard-Coder, a Staff-level AI engineer specializing in \
    feature flag conflict resolution, formal program verification, and risk-aware \
    software delivery. Your analysis is powered by Z3 SAT/SMT solving, NetworkX \
    knowledge graphs, and SHAP-based commit risk quantification. Always cite specific \
    functions, provide unified diffs when suggesting fixes, and quantify business \
    impact with concrete estimates. Be direct, precise, and actionable.\"\"\"

    # ── License & Info ──────────────────────────────────────────────────────
    LICENSE \"\"\"MIT — FlagGuard Project (github.com/your-org/flagguard)\"\"\"
""")

COLAB_MERGE_SCRIPT = textwrap.dedent("""\
    # ══════════════════════════════════════════════════════════════════════
    # Run these cells in Google Colab AFTER DPO training is complete.
    # Merges LoRA adapters into the full model and exports as GGUF.
    # ══════════════════════════════════════════════════════════════════════

    # Cell 1: Load DPO model
    from unsloth import FastLanguageModel

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="{lora_dir}",   # DPO-aligned LoRA adapters
        max_seq_length=2048,
        dtype=None,
        load_in_4bit=True,
    )
    FastLanguageModel.for_inference(model)

    # Cell 2: Export as GGUF (all quantization levels)
    # This step happens on Colab to use their GPU+storage
    model.save_pretrained_gguf(
        "models",
        tokenizer,
        quantization_method="{quant}",
    )
    # Output: models/{gguf_filename}

    # Cell 3: Download the GGUF file and place it in:
    #   models/{gguf_filename}

    # Cell 4: Then run locally:
    #   python scripts/export_gguf.py --lora-dir {lora_dir} --quant {quant}
    #   ollama create flagguard-coder -f models/Modelfile
""")


def _read_adapter_meta(lora_dir: str) -> dict:
    """Read training provenance from adapter_meta.json if it exists."""
    meta_path = Path(lora_dir) / "adapter_meta.json"
    if meta_path.exists():
        try:
            return json.loads(meta_path.read_text())
        except Exception:
            pass
    return {}


def generate_modelfile(
    lora_dir: str,
    quant: str = "q4_k_m",
    output_path: str = "models/Modelfile",
    dry_run: bool = False,
) -> str:
    """Generate the Ollama Modelfile for the fine-tuned model.

    Args:
        lora_dir: Path to DPO LoRA adapter directory (contains adapter_meta.json).
        quant: GGUF quantization level (e.g., "q4_k_m").
        output_path: Where to write the Modelfile.
        dry_run: If True, print the Modelfile but don't write it.

    Returns:
        The Modelfile content as a string.
    """
    if quant not in QUANT_OPTIONS:
        log.warning("Unknown quantization %r. Available: %s", quant, list(QUANT_OPTIONS.keys()))
        quant = "q4_k_m"

    meta = _read_adapter_meta(lora_dir)
    base_model = meta.get("sft_checkpoint", meta.get("base_model", "unsloth/Meta-Llama-3.1-8B-Instruct"))
    quant_info = QUANT_OPTIONS[quant]

    # Derive the GGUF filename from Unsloth's naming convention
    model_short = Path(base_model).name.lower().replace("-", "_").replace(".", "_")
    gguf_filename = f"{model_short}_{quant}.gguf"

    modelfile = MODELFILE_TEMPLATE.format(
        timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        base_model=base_model,
        quant=f"{quant} ({quant_info['desc']})",
        gguf_filename=gguf_filename,
    )

    if dry_run:
        print("\n" + "─" * 60)
        print("MODELFILE PREVIEW (dry-run — not written)")
        print("─" * 60)
        print(modelfile)
        return modelfile

    out_path = Path(output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(modelfile)
    log.info("✅ Modelfile written to %s", output_path)

    return modelfile


def print_deployment_guide(lora_dir: str, quant: str, output_path: str) -> None:
    """Print the complete step-by-step deployment guide."""
    meta = _read_adapter_meta(lora_dir)
    base_model = meta.get("sft_checkpoint", "models/flagguard-sft-lora")
    model_short = Path(base_model).name.lower().replace("-", "_").replace(".", "_")
    gguf_filename = f"{model_short}_{quant}.gguf"
    quant_info = QUANT_OPTIONS.get(quant, {})

    colab_script = COLAB_MERGE_SCRIPT.format(
        lora_dir=lora_dir,
        quant=quant,
        gguf_filename=gguf_filename,
    )

    print("\n" + "═" * 65)
    print("  FLAGGUARD-CODER DEPLOYMENT GUIDE")
    print("═" * 65)
    print(f"\n  Quantization  : {quant}  ({quant_info.get('desc', '')})")
    print(f"  VRAM required : ~{quant_info.get('vram_gb', '?')} GB")
    print(f"  Quality       : {quant_info.get('quality', '?')}")
    print(f"  GGUF file     : models/{gguf_filename}")
    print(f"  Modelfile     : {output_path}")

    print("\n" + "─" * 65)
    print("  STEP 1: Merge LoRA to GGUF (run in Google Colab)")
    print("─" * 65)
    print(colab_script)

    print("─" * 65)
    print("  STEP 2: Local setup")
    print("─" * 65)
    print(f"  # Copy GGUF to models/ then:")
    print(f"  ollama create flagguard-coder -f {output_path}")
    print(f"  ollama run flagguard-coder 'Explain mutual exclusion conflict'")

    print("\n" + "─" * 65)
    print("  STEP 3: Verify FlagGuard auto-detection")
    print("─" * 65)
    print("  ollama list | grep flagguard   # should show flagguard-coder:latest")
    print("  python -c \"from flagguard.llm.ollama_client import OllamaClient; c=OllamaClient(); print(c.config.model)\"")
    print("  # Should print: flagguard-coder:latest")

    # Win rate from metadata
    dpo_eval = meta.get("eval", {})
    win_rate = dpo_eval.get("win_rate")
    if win_rate is not None:
        print(f"\n  DPO Win Rate  : {win_rate:.1%}  (target: > 60%)")
        if win_rate >= 0.6:
            print("  ✅ Model is well-aligned with human preferences.")
        else:
            print("  ⚠️ Win rate below 60% — consider collecting more real feedback or re-training.")

    print("\n" + "═" * 65 + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Ollama Modelfile for FlagGuard-Coder.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--lora-dir", default="models/flagguard-dpo-lora",
                        help="Path to DPO LoRA adapter directory")
    parser.add_argument("--output", default="models/Modelfile",
                        help="Where to write the Ollama Modelfile")
    parser.add_argument("--quant", default="q4_k_m", choices=list(QUANT_OPTIONS.keys()),
                        help="GGUF quantization level")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print Modelfile without writing it to disk")
    parser.add_argument("--list-quants", action="store_true",
                        help="List available quantization options and exit")

    args = parser.parse_args()

    if args.list_quants:
        print("\nAvailable quantization levels:")
        print(f"  {'Key':<10} {'Description':<25} {'VRAM':<10} {'Quality'}")
        print("  " + "─" * 60)
        for key, info in QUANT_OPTIONS.items():
            print(f"  {key:<10} {info['desc']:<25} ~{info['vram_gb']:<9.1f} {info['quality']}")
        print()
        sys.exit(0)

    generate_modelfile(
        lora_dir=args.lora_dir,
        quant=args.quant,
        output_path=args.output,
        dry_run=args.dry_run,
    )

    if not args.dry_run:
        print_deployment_guide(args.lora_dir, args.quant, args.output)


if __name__ == "__main__":
    main()
